"""empty message

Revision ID: bd8586381b8c
Revises: 3e31987abc9f
Create Date: 2024-12-13 07:19:11.680886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8586381b8c'
down_revision: Union[str, None] = '3e31987abc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'category',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(op.f('uq__product__id'), 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__product__id'), 'product', type_='unique')
    op.alter_column('product', 'category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
